apiVersion: v1
kind: Service
metadata:
  name: project7-deployment

spec:
  selector:
    app: project7
  ports:
    - port: 80
      targetPort: 80
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: project7-deployment

spec:
  replicas: 1
  selector:
    matchLabels:
      app: project7
  template:
    metadata:
      labels:
        app: project7
    spec:
      containers:
        - name: project7
          image: fkneist/udacity-project7:latest
          imagePullPolicy: 'Always'
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: '64Mi'
              cpu: '500m'
