---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: project7
  labels:
    app: project7
  namespace: default
spec:
  selector:
    matchLabels:
      app: project7
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: project7
    spec:
      containers:
      - name: project7
        image: fkneist/udacity-project7:latest
        imagePullPolicy: "Always"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: project7
spec:
  selector:
    app: project7
  type: LoadBalancer
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80